"""Table 3: Baseline comparison — ACE vs RAUQ vs SinkProbe (OOB-trustworthy only).

SECONDARY result (E_B1). Carries the 2/4 wins / 1 loss / 1 wash story on the
4 OOB-trustworthy models. Generates LaTeX directly.

CAVEAT preserved in the table caption: this comparison uses the pre-sealed
prep-sweep baselines at gen_step=1 (archived here as
paper/t0/figures/source/head_to_head.csv),
NOT the sealed t=0 ACE locus. Re-running baselines at t=0 is deferred per
the pre-reg's E_B1 non-blocking clause. Honest read for current-state paper.

Usage:
    .venv/bin/python paper/t0/figures/table3_baselines.py
"""
from __future__ import annotations

import csv
from pathlib import Path

HEAD_TO_HEAD = Path(__file__).resolve().parent / "source" / "head_to_head.csv"
OUT_DIR = Path(__file__).resolve().parent / "out"
OUT_DIR.mkdir(exist_ok=True)

# Short-name mapping for the head_to_head model column (which uses MLX slugs)
SHORTEN = {
    "Llama-3.2-3B-Instruct-4bit": "Llama-3.2-3B",
    "Mistral-7B-Instruct-v0.3-4bit": "Mistral-7B",
    "Mistral-Nemo-Instruct-2407-4bit": "Mistral-Nemo",
    "Phi-3.5-mini-instruct-4bit": "Phi-3.5-mini",
    "Phi-4-mini-instruct-4bit": "Phi-4-mini",
    "Qwen2.5-7B-Instruct-4bit": "Qwen2.5-7B",
    "Qwen3-1.7B-4bit": "Qwen3-1.7B",
    "Qwen3-8B-4bit": "Qwen3-8B",
    "gemma-3-4b-it-4bit": "Gemma-3-4B",
}


def _fmt(s: str) -> str:
    if not s:
        return "---"
    try:
        return f"{float(s):.3f}"
    except ValueError:
        return s


def main() -> None:
    with HEAD_TO_HEAD.open() as f:
        rows = list(csv.DictReader(f))

    # OOB-trustworthy only (ours_trust == "clean"). Drop baseline-only Llama-3.1-8B.
    clean = [r for r in rows if r["ours_trust"] == "clean"]

    lines = []
    lines.append("% Table 3 — ACE vs RAUQ vs SinkProbe baselines (E_B1, secondary)")
    lines.append("% Generated by paper/t0/figures/table3_baselines.py")
    lines.append("% Source: paper/t0/figures/source/head_to_head.csv")
    lines.append("% CAVEAT: gen_step=1 prep-sweep numbers (NOT sealed t=0). E_B1 t=0 re-run is non-blocking future work.")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{ACE vs RAUQ vs SinkProbe on OOB-trustworthy models (\textbf{$E_{B1}$, secondary}). ACE wins 2/4 clean (Phi-3.5-mini, Qwen2.5-7B), loses 1 to RAUQ (Llama-3.2-3B), is overtaken by SinkProbe by 0.003 on Qwen3-8B. Numbers are gen\_step=1 OOB AUROC from the May~2026 prep sweep; a sealed $t{=}0$ re-run is non-blocking future work per the pre-reg's $E_{B1}$ clause.}")
    lines.append(r"\label{tab:ace_baselines}")
    lines.append(r"\small")
    lines.append(r"\setlength{\tabcolsep}{6pt}")
    lines.append(r"\begin{tabular}{@{}lrrrl@{}}")
    lines.append(r"\toprule")
    lines.append(r"\textbf{Model} & \textbf{ACE} & \textbf{RAUQ} & \textbf{SinkProbe} & \textbf{Winner} \\")
    lines.append(r"\midrule")

    wins = {"ours": 0, "rauq": 0, "sinkprobe": 0, "wash": 0}
    for r in clean:
        model = SHORTEN.get(r["model"], r["model"])
        ours = float(r["ours_oob"])
        rauq = float(r["rauq_auroc_fixed"])
        sink = float(r["sink_auroc_fixed"])
        # ACE = winner if it leads by >= 0.005
        leader = "ours"
        leader_val = ours
        for name, val in (("rauq", rauq), ("sinkprobe", sink)):
            if val > leader_val:
                leader = name
                leader_val = val
        # Wash = top two within 0.005
        sorted_vals = sorted([("ours", ours), ("rauq", rauq), ("sinkprobe", sink)],
                             key=lambda x: -x[1])
        if sorted_vals[0][1] - sorted_vals[1][1] < 0.005:
            verdict_str = f"wash ({sorted_vals[0][0]} vs {sorted_vals[1][0]})"
            wins["wash"] += 1
        else:
            verdict_str = {"ours": "ACE", "rauq": "RAUQ", "sinkprobe": "SinkProbe"}[leader]
            wins[leader] += 1

        # Bold the winning column
        def bold(name: str, val: float) -> str:
            if leader == name and sorted_vals[0][1] - sorted_vals[1][1] >= 0.005:
                return rf"\textbf{{{val:.3f}}}"
            return f"{val:.3f}"

        lines.append(
            f"{model} & {bold('ours', ours)} & {bold('rauq', rauq)} & "
            f"{bold('sinkprobe', sink)} & {verdict_str} \\\\"
        )

    lines.append(r"\midrule")
    lines.append(
        f"\\multicolumn{{5}}{{l}}{{ACE wins: \\textbf{{{wins['ours']}}}/{len(clean)}  $\\cdot$  "
        f"RAUQ wins: {wins['rauq']}  $\\cdot$  SinkProbe wins: {wins['sinkprobe']}  $\\cdot$  "
        f"washes: {wins['wash']}  (threshold: $\\Delta < 0.005$)}} \\\\"
    )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")

    out_path = OUT_DIR / "table3_baselines.tex"
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path}")
    print(f"  ACE wins {wins['ours']}/{len(clean)}, RAUQ {wins['rauq']}, "
          f"SinkProbe {wins['sinkprobe']}, washes {wins['wash']}")


if __name__ == "__main__":
    main()
