"""Table 2: Per-model winner cells (ANLI + TriviaQA) with OOB CIs + stability.

Carries the per-model detail behind Fig 1/2/3. Generates LaTeX directly to
paper/t0/figures/out/table2_winner_cells.tex.

Usage:
    .venv/bin/python paper/t0/figures/table2_winner_cells.py
"""
from __future__ import annotations

from pathlib import Path

from load_ace_profiles import paired_by_model

OUT_DIR = Path(__file__).resolve().parent / "out"
OUT_DIR.mkdir(exist_ok=True)


def _sign(s: int) -> str:
    return "$+$" if s > 0 else "$-$"


def _fmt(v: float, prec: int = 3) -> str:
    return f"{v:.{prec}f}"


def _tex_escape(s: str) -> str:
    """Escape underscores for LaTeX (most common issue in our metric labels)."""
    return s.replace("_", r"\_")


def _cell_str(rec) -> str:
    cell = f"{rec.block_prefix}_{rec.metric_name}"
    return f"\\texttt{{{_tex_escape(cell)}}} {_sign(rec.sign)}"


def main() -> None:
    pairs = paired_by_model()

    lines = []
    lines.append("% Table 2 — ACE per-model winner cells (ANLI + TriviaQA)")
    lines.append("% Generated by paper/t0/figures/table2_winner_cells.py")
    lines.append("% Source: experiments/t0-sealed/2026-05-26/profiles/")
    lines.append(r"\begin{table*}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{ACE winner cells per model on ANLI R1 and TriviaQA. AUROC reported as OOB bootstrap median with 95\% CI; stability is the OOB winner-cell stability fraction. \textbf{Transfer} marks exact (metric, block, sign) match across datasets.}")
    lines.append(r"\label{tab:ace_winner_cells}")
    lines.append(r"\small")
    lines.append(r"\setlength{\tabcolsep}{4pt}")
    lines.append(r"\begin{tabular}{@{}lllrrlrrc@{}}")
    lines.append(r"\toprule")
    lines.append(r" & \multicolumn{3}{c}{\textbf{ANLI R1} ($n{=}200$)} & \multicolumn{3}{c}{\textbf{TriviaQA} ($n{=}100$)} & \\")
    lines.append(r"\cmidrule(lr){2-4} \cmidrule(lr){5-7}")
    lines.append(r"\textbf{Model} & \textbf{Winner cell} & \textbf{AUROC [CI]} & \textbf{Stab.} & \textbf{Winner cell} & \textbf{AUROC [CI]} & \textbf{Stab.} & \textbf{Transfer} \\")
    lines.append(r"\midrule")

    exact_count = 0
    for anli, triviaqa in pairs:
        exact = anli.winner_triple == triviaqa.winner_triple
        if exact:
            exact_count += 1
        anli_auroc = f"{_fmt(anli.oob_median)} [{_fmt(anli.oob_ci_lo)}, {_fmt(anli.oob_ci_hi)}]"
        triv_auroc = f"{_fmt(triviaqa.oob_median)} [{_fmt(triviaqa.oob_ci_lo)}, {_fmt(triviaqa.oob_ci_hi)}]"
        transfer_mark = r"$\checkmark$" if exact else "---"
        lines.append(
            f"{anli.model_short} & "
            f"{_cell_str(anli)} & {anli_auroc} & {_fmt(anli.stability, 2)} & "
            f"{_cell_str(triviaqa)} & {triv_auroc} & {_fmt(triviaqa.stability, 2)} & "
            f"{transfer_mark} \\\\"
        )

    lines.append(r"\midrule")
    lines.append(
        f"\\multicolumn{{8}}{{r}}{{Exact-transfer count: \\textbf{{{exact_count}/9}} "
        r"$\,\Rightarrow\,$ $E_{A2}$ partial-transfer reframe.} \\"
    )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table*}")

    out_path = OUT_DIR / "table2_winner_cells.tex"
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} ({exact_count}/9 exact transfer)")


if __name__ == "__main__":
    main()
